### ISSUE TITLE
URLs are not URL encoded in links

### ISSUE THREAD

**Issue by Hutchy68** [joomla/help.joomla.org#3]
Go to https://help.joomla.org/proxy?keyref=What_is_the_typical_template_directory_structure%3F

Click link at bottom which shows as: https://docs.joomla.org/What_is_the_typical_template_directory_structure?/en

Link should be formed as:
https://docs.joomla.org/What_is_the_typical_template_directory_structure%3F/en

If this can't be fixed in the proxy, we could do a rewrite for ? to %3F. Thoughts? And yes, we could do it docs side without ? for pages, but with languages it would be a nightmare. Each page would have to be created to redirect with the /{lang code} tacked on.

**Comment by mbabker** [comment]
Probably just needs a `urlencode()` call in the layout file and it should be good.
