### ISSUE TITLE
In CMS version 3.10 the complete help is broken because there is no 3.10 help

### ISSUE THREAD

**Issue by richard67** [joomla/help.joomla.org#32]
Install a clean, current 3.10-dev or latest 3.10.x nightly build.

Check the help links in backend.

E.g. for Banners: [https://help.joomla.org/proxy?keyref=Help310:Components_Banners_Banners&lang=en](https://help.joomla.org/proxy?keyref=Help310:Components_Banners_Banners&lang=en).

Result: 404 not found.

The same link but with "keyref=Help39" instead of "keyref=Help310" works: https://help.joomla.org/proxy?keyref=Help39:Components_Banners_Banners&lang=en

I have no idea how the help docs site works. Maybe it just needs to add a Help310 key or something to the existing 3.9.x docs.

**Comment by conconnl** [comment]
See https://github.com/joomla/joomla-websites/issues/1661 as well.
Link:  https://help.joomla.org/proxy?keyref=Help310:Start_Here&lang=en

Probably there are a lot more.

**Comment by conconnl** [comment]
This one as well:
https://github.com/joomla/joomla-websites/issues/1649

**Comment by conconnl** [comment]
Looking at the source pages:
The 310 category doesn't exist and thus also not connected to articles: 
https://docs.joomla.org/Category:Help_screen_3.9/en

While this one exists: https://docs.joomla.org/Category:Help_screen_3.9/en

**Comment by richard67** [comment]
Has been solved meanwhile, see https://github.com/joomla/joomla-cms/issues/35414#issuecomment-908439057 . Thanks @wilsonge .

**Comment by Franzwohlkoenig** [comment]
Click on help button give 'https://docs3.joomla.com/administrator/help/en-GB/Menus_Menu_Item_Manager.html' and 404 error.

Maybe another issue, should i open a new one?
