### ISSUE TITLE
3.10: No help screen loaded - "404 Category not found"

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla/help.joomla.org#33]
Click on help button give 'https://docs3.joomla.com/administrator/help/en-GB/Menus_Menu_Item_Manager.html' and 404 error 'Category not found '.

The URL is an example, 404 happens on all help screens i used.

#32 is closed as resolved so this issue is maybe another issue.

**Comment by Franzwohlkoenig** [comment]
Looks like no other have this issue.

**Comment by MartijnMaandag** [comment]
I tried this with an existing 3.10 site and after this I did make a new installation.
Both give https://help.joomla.org/proxy?keyref=Help310:Menus_Menu_Manager&lang=en  and no 404

**Comment by Franzwohlkoenig** [comment]
Thanks @MartijnMaandag for taking time to test. Closing as its an issue on my side.
